name: Laravel CI with Passport and PostgreSQL

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports: ['5432:5432']
        env:
          POSTGRES_USER: ${{ secrets.DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_DATABASE }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, pdo, pdo_pgsql

    - name: Create .env file
      run: |
        cp .env.example .env
        echo "APP_ENV=testing" >> .env
        echo "APP_KEY=" >> .env
        echo "DB_CONNECTION=pgsql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=5432" >> .env
        echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
        echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "PASSPORT_CLIENT_ID=${{ secrets.PASSPORT_CLIENT_ID }}" >> .env
        echo "PASSPORT_CLIENT_SECRET=${{ secrets.PASSPORT_CLIENT_SECRET }}" >> .env

    - name: Install Composer dependencies
      run: composer install --no-progress --no-scripts --prefer-dist

    - name: Generate application key
      run: php artisan key:generate

    - name: Set storage and cache permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Run database migrations
      run: php artisan migrate --force

    - name: Run Feature and Unit tests
      run: php artisan test
